### ISSUE TITLE
How to generate video features 

### ISSUE THREAD

**Issue by yujialele** [benedettaliberatori/T3AL#7]
Thank you for your best work! please provide some details about vosual features generation. How to obtain the feature frame in the annotation.json?

**Comment by benedettaliberatori** [comment]
Hi, thank you for your interest in our work!

Could you please clarify what you mean by _frame feature in the .json_?
It comes from the [original file](https://raw.githubusercontent.com/activitynet/ActivityNet/refs/heads/master/Evaluation/data/activity_net.v1-3.min.json) for ActivityNet. You can get the same file for THUMOS14 starting from the original annotations, in order to have a consistent format for both. 
I hope I answered your question. If not, I look forward to your clarification!
